/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zoe_jnitest_Nadd */

#ifndef _Included_com_zoe_jnitest_Nadd
#define _Included_com_zoe_jnitest_Nadd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zoe_jnitest_Nadd
 * Method:    nadd
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zoe_jnitest_Nadd_nadd
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
